from domain.interfaces.repository.failure_repository import IFailureRepository
from domain.interfaces.repository.user_repository import IUserRepository
from domain.interfaces.repository.user_info_repository import IUserInfoRepository
from domain.interfaces.repository.user_account_repository import IUserAccountRepository
