from domain.requests.create_failure_request import CreateFailureRequest
from domain.requests.delete_failure_request import DeleteFailureRequest
from domain.requests.update_failure_request import UpdateFailureRequest
from domain.requests.get_user_info_request import GetUserInfoRequest
from domain.requests.register_user_request import RegisterUserRequest
from domain.requests.authorization_request import AuthorizationRequest
